'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {createLocalRoomRepository} from '../../lib/persistence/local-repositories';
import type {RoomDayRecord as DayRecord,RoomStatus as Status,RoomZoneId as ZoneId} from '../../features/room/domain';
import './metrics.css';
const label:Record<Status,string>={ok:'En orden',review:'Hubo algo que revisar',attention:'Requirió atención'}; const zoneLabel:Record<ZoneId,string>={bed:'Cama',desk:'Escritorio',tv:'Zona de TV',closet:'Clóset'};
const dayName=(date:string)=>new Intl.DateTimeFormat('es-MX',{weekday:'short'}).format(new Date(`${date}T12:00:00`)).replace('.','');
const shortDate=(date:string)=>new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short'}).format(new Date(`${date}T12:00:00`)).replace('.','');
export default function Metricas(){const [history,setHistory]=useState<DayRecord[]>([]);useEffect(()=>{queueMicrotask(()=>{createLocalRoomRepository().loadDailyHistory().then(setHistory).catch(()=>{})})},[]);const days=useMemo(()=>history.slice(-7).reverse(),[history]);const allGood=days.filter(d=>d.status==='ok').length;return <main className="metrics-shell"><header className="metrics-top"><div><p className="eyebrow">Mi espacio</p><h1>Así fue tu semana</h1></div><Link href="/" className="back-link">← Volver al plano</Link></header><section className="metrics-intro"><p>Un recuerdo sencillo de cómo cerraste cada día.</p>{days.length>0&&<strong><span>{allGood}</span> {allGood===1?'día':'días'} en orden</strong>}</section>{days.length===0?<section className="no-history"><span>✦</span><h2>Tu historia empieza hoy</h2><p>Cuando abras la página en un día nuevo, se guardará cómo terminaste el anterior. Aquí aparecerán tus últimos siete días.</p><Link href="/">Volver a mi habitación</Link></section>:<><section className="week-path" aria-label="Historial de los últimos siete días">{days.map((day,index)=><article key={day.date} className={`day-card ${day.status}`}><div className="day-number"><span>{dayName(day.date)}</span><b>{new Date(`${day.date}T12:00:00`).getDate()}</b></div><div className="day-story"><span className="status-mark">{day.status==='ok'?'✓':day.status==='review'?'—':'!'}</span><div><p>{index===0?'Ayer':shortDate(day.date)}</p><h2>{label[day.status]}</h2></div></div><div className="zone-trace">{(Object.keys(day.zones) as ZoneId[]).map(zone=><span key={zone} className={day.zones[zone]} title={`${zoneLabel[zone]}: ${label[day.zones[zone]]}`}>{zoneLabel[zone].slice(0,1)}</span>)}</div></article>)}</section><section className="legend-history"><span><i className="ok"/> En orden</span><span><i className="review"/> Revisar</span><span><i className="attention"/> Atención</span><p>Las letras muestran el estado final de cada zona: Cama, Escritorio, TV y Clóset.</p></section></>}</main>}
