'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { createLocalRoomRepository } from '../../lib/persistence/local-repositories';
import { calculateAvailableBalance } from '../finance/domain';
import { useFinance } from '../finance/use-finance';
import { goalPercentage } from '../goals/domain';
import { useGoals } from '../goals/use-goals';
import { useProjects } from '../projects/use-projects';
import { deriveRoomView, ROOM_ZONE_IDS } from '../room/domain';
import { enrollmentStatus } from '../school/domain';
import { useSchool } from '../school/use-school';
import { useSettings } from '../settings/use-settings';
import { isToday, localToday } from '../tasks/domain';
import { useTasks } from '../tasks/use-tasks';

const modules = { tasks: ['Tareas', '/tareas'], finance: ['Finanzas', '/finanzas'], goals: ['Metas', '/metas'], projects: ['Proyectos', '/proyectos'], school: ['Prepa', '/prepa'], room: ['Habitación', '/habitacion'], ideas: ['Ideas', '/ideas'], history: ['Historial', '/historial'] } as const;
const phrases = ['¿Qué quieres organizar hoy?', '¿Qué quieres revisar hoy?', '¿Por dónde quieres empezar hoy?', '¿Qué quieres poner en orden hoy?'];
const greetingForHour = (hour: number) => hour < 12 ? 'Buenos días' : hour < 19 ? 'Buenas tardes' : 'Buenas noches';
const addDays = (date: string, amount: number) => { const value = new Date(`${date}T12:00:00`); value.setDate(value.getDate() + amount); return value.toLocaleDateString('en-CA'); };

export function HomePage() {
  const [greeting, setGreeting] = useState('Buenos días'); const [phrase, setPhrase] = useState(phrases[0]); const [roomAttention, setRoomAttention] = useState(0);
  const { tasks } = useTasks(); const { accounts, transactions, payments } = useFinance(); const { projects } = useProjects(); const { goals } = useGoals(); const { modules: schoolModules, subjects, enrollments } = useSchool(); const { settings } = useSettings(); const today = localToday();
  const pendingTasks = tasks.filter((task) => task.status === 'pending'); const todayTasks = pendingTasks.filter((task) => isToday(task, today)).slice(0, 3); const activeProjects = projects.filter((project) => project.status === 'active'); const activeGoals = goals.filter((goal) => goalPercentage(goal) < 100); const upcomingPayments = payments.filter((payment) => payment.active && payment.next_due_date >= today && payment.next_due_date <= addDays(today, 7)).slice(0, 2); const available = calculateAvailableBalance(accounts, transactions);
  const completed = useMemo(() => new Set(enrollments.filter((item) => item.final_grade !== null).map((item) => item.subject_id)), [enrollments]); const currentModule = schoolModules.find((module) => subjects.some((subject) => subject.module_id === module.id && !completed.has(subject.id))); const currentModuleSubjects = subjects.filter((subject) => subject.module_id === currentModule?.id); const schoolProgress = currentModuleSubjects.length ? Math.round(currentModuleSubjects.filter((subject) => completed.has(subject.id)).length / currentModuleSubjects.length * 100) : 0; const currentEnrollment = enrollments.find((item) => { const status = enrollmentStatus(item, today); return status === 'studying' || status === 'upcoming' || status === 'awaiting_grade'; }); const currentSubject = subjects.find((subject) => subject.id === currentEnrollment?.subject_id); const saturdayClass = new Date(`${today}T12:00:00`).getDay() === 6 && currentEnrollment && enrollmentStatus(currentEnrollment, today) === 'studying';
  useEffect(() => { queueMicrotask(() => { setGreeting(greetingForHour(new Date().getHours())); setPhrase(phrases[Math.floor(Math.random() * phrases.length)]); void createLocalRoomRepository().loadSession().then((session) => { const view = deriveRoomView(session.state); setRoomAttention(ROOM_ZONE_IDS.filter((id) => view[id] !== 'ok').length); }).catch(() => {}); }); }, []);
  const detail = (id: keyof typeof modules) => { if (id === 'tasks') return `${pendingTasks.length} ${pendingTasks.length === 1 ? 'pendiente' : 'pendientes'}`; if (id === 'finance') return accounts.length ? `${new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(available)} disponibles` : 'Aún sin cuentas'; if (id === 'projects') return `${activeProjects.length} ${activeProjects.length === 1 ? 'activo' : 'activos'}`; if (id === 'goals') return `${activeGoals.length} ${activeGoals.length === 1 ? 'activa' : 'activas'}`; if (id === 'school') return currentModule ? `${currentModule.name} · ${schoolProgress}%` : 'Plan BIS'; if (id === 'room') return roomAttention ? `${roomAttention} por revisar` : 'En orden'; if (id === 'ideas') return 'Captura lo que se te ocurra'; return 'Actividad real de tu espacio'; };
  const orderedModules = settings.home_module_order.filter((id) => settings.visible_modules.includes(id)); const hasToday = todayTasks.length > 0 || upcomingPayments.length > 0 || saturdayClass || roomAttention > 0;
  return <main className="foundation-page home-page"><header className="foundation-page__header"><div><p className="foundation-page__eyebrow">Mi espacio</p><h1 className="foundation-page__title">Mi habitación</h1></div></header><section className="home-page__greeting"><h2>{greeting}, {settings.profile_name}</h2><p>{phrase}</p></section><section className="home-page__modules" aria-label="Módulos">{orderedModules.map((id) => { const [name, href] = modules[id]; return <Link key={id} href={href} className={`foundation-card home-module-card ${id === 'room' ? 'home-module-card--accent' : ''}`}><span className="home-module-card__name"><strong>{name}</strong><span>{detail(id)}</span></span><span className="home-module-card__arrow">›</span></Link>; })}</section>{hasToday && <section className="home-page__today"><div className="home-page__today-heading"><h2>Hoy</h2></div><div className="home-page__today-list">{saturdayClass && <Link href="/prepa" className="foundation-card home-today-task"><span>◷</span><span><strong>Clase · {currentSubject?.name}</strong><small>{settings.school.start_time}–{settings.school.end_time}</small></span><span>›</span></Link>}{todayTasks.map((task) => <Link key={task.id} href="/tareas" className="foundation-card home-today-task"><span className="home-today-task__dot"/><span><strong>{task.title}</strong>{task.due_time && <small>{task.due_time}</small>}</span><span>›</span></Link>)}{upcomingPayments.map((payment) => <Link key={payment.id} href="/finanzas" className="foundation-card home-today-task"><span>◌</span><span><strong>{payment.name}</strong><small>Vence {payment.next_due_date}</small></span><strong>{new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(payment.amount)}</strong></Link>)}{roomAttention > 0 && <Link href="/habitacion" className="foundation-card home-today-task"><span className="home-today-task__dot"/><span><strong>Habitación</strong><small>{roomAttention} {roomAttention === 1 ? 'zona requiere' : 'zonas requieren'} atención</small></span><span>›</span></Link>}</div></section>}</main>;
}
