'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { createRoomRepository } from '../../lib/persistence/repositories';
import { calculateAvailableBalance } from '../finance/domain';
import { useFinance } from '../finance/use-finance';
import { goalPercentage } from '../goals/domain';
import { useGoals } from '../goals/use-goals';
import { useIdeas } from '../ideas/use-ideas';
import { useProjects } from '../projects/use-projects';
import { deriveOverallRoomStatus, deriveRoomCounts, deriveRoomView, ROOM_ZONE_IDS, ROOM_STATUS_LABEL, type RoomState } from '../room/domain';
import { enrollmentStatus } from '../school/domain';
import { useSchool } from '../school/use-school';
import { useSettings } from '../settings/use-settings';
import { isToday, localToday } from '../tasks/domain';
import { useTasks } from '../tasks/use-tasks';
import { TaskStatusButton } from '../../components/ui/TaskStatusButton';

const phrases = ['¿Qué quieres organizar hoy?', '¿Qué quieres revisar hoy?', '¿Por dónde quieres empezar hoy?', '¿Qué quieres poner en orden hoy?'];
const greetingForHour = (hour: number) => hour < 12 ? 'Buenos días' : hour < 19 ? 'Buenas tardes' : 'Buenas noches';
const addDays = (date: string, amount: number) => { const value = new Date(`${date}T12:00:00`); value.setDate(value.getDate() + amount); return value.toLocaleDateString('en-CA'); };
const money = (value: number) => new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(value);

export function HomePage() {
  const [greeting, setGreeting] = useState('Buenos días'); const [phrase, setPhrase] = useState(phrases[0]); const [roomState, setRoomState] = useState<RoomState | null>(null);
  const { tasks, pendingTaskIds, setTaskStatus } = useTasks(); const { accounts, transactions, payments } = useFinance(); const { projects } = useProjects(); const { goals } = useGoals(); const { modules: schoolModules, subjects, enrollments } = useSchool(); const { ideas } = useIdeas(); const { settings } = useSettings(); const today = localToday();
  const pendingTasks = tasks.filter((task) => task.status === 'pending'); const todayTasks = pendingTasks.filter((task) => isToday(task, today)); const activeProjects = projects.filter((project) => project.status === 'active');
  const activeGoals = goals.filter((goal) => goalPercentage(goal, tasks) < 100).sort((a, b) => (a.priority === 'main' ? -1 : b.priority === 'main' ? 1 : 0)); const upcomingPayments = payments.filter((payment) => payment.active && payment.next_due_date >= today && payment.next_due_date <= addDays(today, 7)).slice(0, 2); const available = calculateAvailableBalance(accounts, transactions); const recentTransactions = transactions.slice().sort((a, b) => b.date.localeCompare(a.date)).slice(0, 2);
  const completed = useMemo(() => new Set(enrollments.filter((item) => item.final_grade !== null).map((item) => item.subject_id)), [enrollments]); const currentModule = schoolModules.find((module) => subjects.some((subject) => subject.module_id === module.id && !completed.has(subject.id))); const currentModuleSubjects = subjects.filter((subject) => subject.module_id === currentModule?.id); const schoolProgress = currentModuleSubjects.length ? Math.round(currentModuleSubjects.filter((subject) => completed.has(subject.id)).length / currentModuleSubjects.length * 100) : 0; const currentEnrollment = enrollments.find((item) => ['studying', 'upcoming', 'awaiting_grade'].includes(enrollmentStatus(item, today))); const currentSubject = subjects.find((subject) => subject.id === currentEnrollment?.subject_id); const saturdayClass = new Date(`${today}T12:00:00`).getDay() === 6 && currentEnrollment && enrollmentStatus(currentEnrollment, today) === 'studying';
  const roomView = roomState ? deriveRoomView(roomState) : null; const roomCounts = roomState ? deriveRoomCounts(roomState) : null; const roomStatus = roomState ? deriveOverallRoomStatus(roomState) : null; const roomRelevant = roomState ? ROOM_ZONE_IDS.filter((id) => roomView?.[id] !== 'ok').slice(0, 2) : []; const recentIdeas = ideas.filter((idea) => idea.status === 'active').slice(0, 2);
  useEffect(() => { queueMicrotask(() => { setGreeting(greetingForHour(new Date().getHours())); setPhrase(phrases[Math.floor(Math.random() * phrases.length)]); void createRoomRepository().loadSession().then((session) => setRoomState(session.state)).catch(() => {}); }); }, []);
  const hasToday = todayTasks.length > 0 || upcomingPayments.length > 0 || saturdayClass || Boolean(roomCounts?.attention || roomCounts?.review);
  return <main className="foundation-page home-page">
    <section className="home-page__greeting"><h1>{greeting}, {settings.profile_name}</h1><p>{phrase}</p></section>
    <section className="home-page__today" aria-labelledby="home-today-title"><div className="home-page__today-heading"><h2 id="home-today-title">Hoy</h2><span>{hasToday ? 'Lo que requiere tu atención' : 'Todo tranquilo por ahora'}</span></div>{hasToday ? <div className="home-page__today-list">{saturdayClass && <Link href="/prepa" className="foundation-card home-today-task"><span>◷</span><span><strong>Clase · {currentSubject?.name}</strong><small>{settings.school.start_time}–{settings.school.end_time}</small></span><span>›</span></Link>}{todayTasks.slice(0, 3).map((task) => <article key={task.id} className="foundation-card home-today-task"><TaskStatusButton task={task} pending={pendingTaskIds.has(task.id)} onToggle={() => { void setTaskStatus(task, 'completed', goals).catch(() => {}); }}/><Link href="/tareas"><strong>{task.title}</strong>{task.due_time && <small>{task.due_time}</small>}</Link><span>›</span></article>)}{upcomingPayments.slice(0, 1).map((payment) => <Link key={payment.id} href="/finanzas" className="foundation-card home-today-task"><span>◌</span><span><strong>{payment.name}</strong><small>Vence {payment.next_due_date}</small></span><strong>{money(payment.amount)}</strong></Link>)}{roomCounts && (roomCounts.attention + roomCounts.review) > 0 && <Link href="/habitacion" className="foundation-card home-today-task"><span className="home-today-task__dot"/><span><strong>Habitación</strong><small>{roomCounts.attention + roomCounts.review} zona(s) requieren atención</small></span><span>›</span></Link>}</div> : <div className="home-empty-note">No hay nada urgente. Puedes continuar a tu ritmo.</div>}</section>
    <section className="home-page__summaries" aria-label="Resumen de módulos">
      <Link href="/tareas" className="foundation-card home-summary home-summary--tasks"><header><span className="home-summary__icon">✓</span><span><small>Tareas</small><strong>{pendingTasks.length ? `${pendingTasks.length} pendientes` : 'Sin pendientes'}</strong></span><b>›</b></header><p>{todayTasks.length ? todayTasks.slice(0, 2).map((task) => task.title).join(' · ') : 'No hay tareas para hoy'}</p></Link>
      <Link href="/finanzas" className="foundation-card home-summary"><header><span className="home-summary__icon">$</span><span><small>Finanzas</small><strong>{accounts.length ? money(available) : 'Sin cuentas'}</strong></span><b>›</b></header><p>{recentTransactions.length ? recentTransactions.map((item) => `${item.type === 'income' ? '+' : '-'}${money(item.amount)}`).join(' · ') : upcomingPayments.length ? `${upcomingPayments.length} pago(s) próximos` : 'Aún sin movimientos'}</p></Link>
      <Link href="/metas" className="foundation-card home-summary"><header><span className="home-summary__icon">◎</span><span><small>Metas</small><strong>{activeGoals.length ? activeGoals[0].name : 'Sin metas activas'}</strong></span><b>›</b></header>{activeGoals.length ? <><div className="home-summary__progress"><i style={{ width: `${goalPercentage(activeGoals[0], tasks)}%` }} /></div><p>{goalPercentage(activeGoals[0], tasks)}% completada</p></> : <p>Crea una meta cuando quieras</p>}</Link>
      <Link href="/proyectos" className="foundation-card home-summary"><header><span className="home-summary__icon">◈</span><span><small>Proyectos</small><strong>{activeProjects.length ? `${activeProjects.length} activos` : 'Sin proyectos activos'}</strong></span><b>›</b></header><p>{activeProjects[0]?.name ?? 'Tu siguiente proyecto puede empezar aquí'}</p></Link>
      <Link href="/prepa" className="foundation-card home-summary"><header><span className="home-summary__icon">⌂</span><span><small>Prepa</small><strong>{currentSubject?.name ?? currentModule?.name ?? 'Plan BIS'}</strong></span><b>›</b></header><p>{saturdayClass ? `Clase hoy · ${settings.school.start_time}–${settings.school.end_time}` : currentModule ? `${currentModule.name} · ${schoolProgress}%` : 'Sin cursado activo'}</p></Link>
      <Link href="/habitacion" className="foundation-card home-summary"><header><span className="home-summary__icon">⌘</span><span><small>Habitación</small><strong>{roomStatus ? ROOM_STATUS_LABEL[roomStatus] : 'Cargando estado'}</strong></span><b>›</b></header><p>{roomCounts ? `${roomCounts.review + roomCounts.attention} zona(s) para revisar` : 'Revisa tu espacio'}</p>{roomRelevant.length > 0 && <small className="home-summary__detail">{roomRelevant.join(' · ')}</small>}</Link>
      <Link href="/ideas" className="foundation-card home-summary home-summary--ideas"><header><span className="home-summary__icon">✦</span><span><small>Ideas</small><strong>{recentIdeas.length ? `${recentIdeas.length} recientes` : 'Captura una idea'}</strong></span><b>›</b></header><p>{recentIdeas[0]?.content ?? '¿Qué se te ocurrió?'}</p></Link>
    </section>
  </main>;
}
