'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
type Status='ok'|'review'|'attention'; type ZoneId='bed'|'desk'|'tv'|'closet'; type Item=ZoneId|'tvUnit'|'shoeShelf'|'dresser'|'hanging'|'laundry'|'cubbies'; type Filter='all'|'attention'|'ok'; type RoomState=Record<Item,Status>; type Updated=Partial<Record<Item,number>>;
const KEY='mi-habitacion:v3', OLD_KEY='mi-habitacion:v2';
const rank:Record<Status,number>={ok:0,review:1,attention:2}; const label:Record<Status,string>={ok:'En orden',review:'Revisar',attention:'Requiere atención'};
const defaults:RoomState={bed:'attention',desk:'review',tv:'ok',closet:'ok',tvUnit:'ok',shoeShelf:'ok',dresser:'ok',hanging:'ok',laundry:'ok',cubbies:'ok'};
const childMap:Partial<Record<ZoneId,Item[]>>={tv:['tvUnit','shoeShelf'],closet:['dresser','hanging','laundry','cubbies']};
const today=()=>new Date().toLocaleDateString('en-CA'); const worst=(items:Status[])=>items.reduce((a,b)=>rank[b]>rank[a]?b:a,'ok');
const timestamp=()=>Date.now();
type DayRecord={date:string;status:Status;zones:Record<ZoneId,Status>};
const snapshot=(value:RoomState,date:string):DayRecord=>{const zones={bed:value.bed,desk:value.desk,tv:worst([value.tvUnit,value.shoeShelf]),closet:worst([value.dresser,value.hanging,value.laundry,value.cubbies])};return {date,status:worst(Object.values(zones)),zones}};
const formatUpdated=(value?:number)=>value?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(value):'Sin cambios registrados';
function Dot({status}:{status:Status}){return <span className={`dot ${status}`} aria-hidden="true"/>}

export default function Home(){
 const [state,setState]=useState<RoomState>(defaults),[updated,setUpdated]=useState<Updated>({}),[history,setHistory]=useState<DayRecord[]>([]),[notifications,setNotifications]=useState(false),[selected,setSelected]=useState<{id:Item;name:string}|null>(null),[filter,setFilter]=useState<Filter>('all'),[confirmReset,setConfirmReset]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{queueMicrotask(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||'null');if(saved?.state){const next={...defaults,...saved.state},times=saved.updated||{};let previous:DayRecord[]=saved.history||[];if(saved.date!==today()){const record=snapshot(next,saved.date);previous=[...previous.filter((entry:DayRecord)=>entry.date!==record.date),record].slice(-365);next.bed='attention';times.bed=Date.now()}setState(next);setUpdated(times);setHistory(previous);setNotifications(Boolean(saved.notifications))}}catch{}setReady(true)})},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify({version:4,date:today(),state,updated,history,notifications}))},[ready,state,updated,history,notifications]);
 const view=useMemo(()=>({...state,tv:worst([state.tvUnit,state.shoeShelf]),closet:worst([state.dresser,state.hanging,state.laundry,state.cubbies])}),[state]);
 const counts=useMemo(()=>(['bed','desk','tv','closet'] as ZoneId[]).reduce((all,id)=>({...all,[view[id]]:all[view[id]]+1}),{ok:0,review:0,attention:0}),[view]);
 const overall=worst([view.bed,view.desk,view.tv,view.closet]); const visible=(status:Status)=>filter==='all'||status===filter;
 useEffect(()=>{if(!ready||!notifications||typeof Notification==='undefined'||Notification.permission!=='granted')return;const check=()=>{if(overall==='ok')return;const wait=overall==='attention'?60*60*1000:8*60*60*1000;const last=Number(localStorage.getItem('mi-habitacion:last-notification')||0);if(Date.now()-last<wait)return;const body=overall==='attention'?'Hay una zona que requiere atención.':'Hay una zona que conviene revisar.';const send=()=>{localStorage.setItem('mi-habitacion:last-notification',String(Date.now()))};navigator.serviceWorker?.ready.then(reg=>reg.showNotification('Mi habitación',{body,icon:'/app-icon.svg',tag:'mi-habitacion-order'}).then(send)).catch(()=>{new Notification('Mi habitación',{body,icon:'/app-icon.svg',tag:'mi-habitacion-order'});send()})};check();const timer=window.setInterval(check,60*1000);return()=>window.clearInterval(timer)},[ready,notifications,overall]);
 const toggleNotifications=async()=>{if(notifications){setNotifications(false);return}if(typeof Notification==='undefined')return;const permission=await Notification.requestPermission();if(permission==='granted')setNotifications(true)};
 const lastUpdated=(id:Item)=>childMap[id as ZoneId]?.reduce((last,child)=>Math.max(last,updated[child]||0),0)||updated[id];
 const setStatus=(status:Status)=>{if(!selected)return;const now=timestamp(),kids=childMap[selected.id as ZoneId];if(kids){setState(p=>({...p,...Object.fromEntries(kids.map(id=>[id,status]))}));setUpdated(p=>({...p,...Object.fromEntries(kids.map(id=>[id,now])),[selected.id]:now}))}else{setState(p=>({...p,[selected.id]:status}));setUpdated(p=>({...p,[selected.id]:now}))}setSelected(null)};
 const resetDay=()=>{const now=timestamp();setState(p=>({...p,bed:'attention'}));setUpdated(p=>({...p,bed:now}));setConfirmReset(false)};
 const currentSelected=selected?(childMap[selected.id as ZoneId]?view[selected.id as ZoneId]:state[selected.id]):'ok';
 return <main className="shell">
  <header className="top"><div><p className="eyebrow">Mi espacio</p><h1>Mi habitación</h1></div><div className="top-actions"><Link className="history-link" href="/metricas" aria-label="Abrir historial" title="Historial"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 19V5"/><path d="M4 19h16"/><path d="m7 15 4-4 3 2 4-5"/></svg></Link><button className={`notify-button ${notifications?'enabled':''}`} onClick={toggleNotifications} aria-pressed={notifications} aria-label={notifications?'Desactivar avisos':'Activar avisos'} title={notifications?'Avisos activados':'Activar avisos'}><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></svg></button><button className="reset-button" onClick={()=>setConfirmReset(true)}>↻ <span>Reiniciar día</span></button></div></header>
  <section className="daily-summary" aria-label="Resumen de estados"><Summary status="ok" count={counts.ok} text="En orden" active={filter==='ok'} onClick={()=>setFilter('ok')}/><Summary status="review" count={counts.review} text="Revisar" active={false} onClick={()=>setFilter('all')}/><Summary status="attention" count={counts.attention} text="Atención" active={filter==='attention'} onClick={()=>setFilter('attention')}/><div className="overall"><Dot status={overall}/><span>Estado general<br/><b>{label[overall]}</b></span></div></section>
  <section className="intro"><div><p className="date">HOY · {new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase()}</p><h2>¿Cómo está tu espacio?</h2><p>Toca una zona para actualizarla.</p></div><div className="view-tools"><div className="filters" role="group" aria-label="Filtrar plano">{([['all','Todo'],['attention','Requiere atención'],['ok','En orden']] as [Filter,string][]).map(([id,text])=><button key={id} aria-pressed={filter===id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{text}</button>)}</div><div className="status-key" aria-label="Leyenda de estados"><span><Dot status="ok"/>✓ En orden</span><span><Dot status="review"/>— Revisar</span><span><Dot status="attention"/>! Atención</span></div></div></section>
  <section className="room" aria-label="Plano de la habitación"><div className="window" aria-hidden="true"><i/><i/><i/></div>
   <ZoneButton id="bed" name="Cama" status={view.bed} visible={visible(view.bed)} className="bed" onOpen={setSelected}><span className="furniture bed-shape"><i/><i/></span></ZoneButton>
   <ZoneButton id="desk" name="Escritorio" status={view.desk} visible={visible(view.desk)} className="desk" onOpen={setSelected}><span className="furniture desk-shape"><i/><i/><i/></span></ZoneButton>
   <Group id="tv" title="Zona de TV" status={view.tv} visible={visible(view.tv)} className="tv" onOpen={setSelected}><Sub id="tvUnit" name="Mueble de TV" status={state.tvUnit} onOpen={setSelected}/><Sub id="shoeShelf" name="Estantería / mueble de zapatos" status={state.shoeShelf} onOpen={setSelected}/></Group>
   <Group id="closet" title="Clóset" status={view.closet} visible={visible(view.closet)} className="closet" onOpen={setSelected}><div className="closet-grid"><Sub id="dresser" name="Cómoda" status={state.dresser} onOpen={setSelected}/><Sub id="hanging" name="Ropa colgada" status={state.hanging} onOpen={setSelected}/><Sub id="laundry" name="Ropa sucia" status={state.laundry} onOpen={setSelected}/><Sub id="cubbies" name="Cubículos" status={state.cubbies} onOpen={setSelected}/></div></Group><div className="door" aria-hidden="true"><span/></div>
  </section>{filter!=='all'&&counts[filter]===0&&<p className="empty-filter" role="status"><span>✓</span>No hay zonas en “{label[filter]}”. <button onClick={()=>setFilter('all')}>Ver todo el plano</button></p>}<p className="privacy"><span>✓</span> Todo se guarda únicamente en este dispositivo</p>
  {selected&&<div className="overlay" onMouseDown={()=>setSelected(null)}><section className="sheet" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onMouseDown={e=>e.stopPropagation()}><div className="grabber"/><p className="eyebrow">Cambiar estado</p><h2 id="dialog-title">{selected.name}</h2><p className="last-updated">Última actualización: <b>{formatUpdated(lastUpdated(selected.id))}</b></p>{childMap[selected.id as ZoneId]&&<p className="parent-note">Al cambiar esta zona, se actualizarán todas sus subzonas.</p>}<div className="options">{(['ok','review','attention'] as Status[]).map(status=><button key={status} className={currentSelected===status?'active':''} onClick={()=>setStatus(status)}><Dot status={status}/><span><b>{label[status]}</b><small>{status==='ok'?'Todo está en su lugar':status==='review'?'Conviene darle un vistazo':'Necesita ordenarse'}</small></span><i>{currentSelected===status?'✓':''}</i></button>)}</div><button className="cancel" onClick={()=>setSelected(null)}>Cancelar</button></section></div>}
  {confirmReset&&<div className="overlay confirm-overlay" onMouseDown={()=>setConfirmReset(false)}><section className="confirm" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" onMouseDown={e=>e.stopPropagation()}><span className="reset-icon">↻</span><h2 id="confirm-title">¿Reiniciar el día?</h2><p>Solo la cama volverá a “Requiere atención”. El resto de la habitación no cambiará.</p><button className="confirm-action" onClick={resetDay}>Sí, reiniciar la cama</button><button className="cancel" onClick={()=>setConfirmReset(false)}>Cancelar</button></section></div>}
 </main>
}
function Summary({status,count,text,active,onClick}:{status:Status;count:number;text:string;active:boolean;onClick:()=>void}){return <button aria-label={`${count} zonas: ${text}`} aria-pressed={active} onClick={onClick} className={active?'active':''}><Dot status={status}/><strong>{count}</strong><span>{text}</span></button>}
function ZoneButton({id,name,status,visible,className,onOpen,children}:{id:Item;name:string;status:Status;visible:boolean;className:string;onOpen:(v:{id:Item;name:string})=>void;children:React.ReactNode}){return <button aria-label={`${name}: ${label[status]}. Abrir detalle`} className={`zone ${className} ${status} ${visible?'':'filtered-out'}`} onClick={()=>onOpen({id,name})}>{children}<span className="zone-label"><Dot status={status}/><b>{name}</b><small><i aria-hidden="true">{status==='ok'?'✓':status==='review'?'—':'!'}</i>{label[status]}</small></span></button>}
function Group({id,title,status,visible,className,onOpen,children}:{id:ZoneId;title:string;status:Status;visible:boolean;className:string;onOpen:(v:{id:Item;name:string})=>void;children:React.ReactNode}){return <section aria-label={`${title}: ${label[status]}`} className={`zone group ${className} ${status} ${visible?'':'filtered-out'}`}><button aria-label={`${title}: ${label[status]}. Cambiar toda la zona`} className="group-title" onClick={()=>onOpen({id,name:title})}><Dot status={status}/><div><h3>{title}</h3><p><i aria-hidden="true">{status==='ok'?'✓':status==='review'?'—':'!'}</i>{label[status]}</p></div><b aria-hidden="true">›</b></button><div className="subzones">{children}</div></section>}
function Sub({id,name,status,onOpen}:{id:Item;name:string;status:Status;onOpen:(v:{id:Item;name:string})=>void}){return <button aria-label={`${name}: ${label[status]}. Abrir detalle`} onClick={()=>onOpen({id,name})}><Dot status={status}/><span><b>{name}</b><small><i aria-hidden="true">{status==='ok'?'✓':status==='review'?'—':'!'}</i>{label[status]}</small></span><b aria-hidden="true">›</b></button>}
