'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { PageHeader } from '../../components/ui/PageHeader';
import { createLocalActivityRepository } from '../../lib/persistence/local-activity-repository';
import type { ActivityLogEntry } from './domain';
type Filter = 'all' | 'tasks' | 'money' | 'projects' | 'goals' | 'school' | 'room' | 'ideas';
const labels: Record<Filter, string> = { all: 'Todo', tasks: 'Tareas', money: 'Dinero', projects: 'Proyectos', goals: 'Metas', school: 'Prepa', room: 'Habitación', ideas: 'Ideas' };
const filterFor = (item: ActivityLogEntry): Filter => item.entity_type === 'task' ? 'tasks' : item.entity_type === 'finance_transaction' || item.entity_type === 'recurring_payment' || item.entity_type === 'saving_goal' ? 'money' : item.entity_type === 'project' ? 'projects' : item.entity_type === 'goal' ? 'goals' : item.entity_type === 'subject_enrollment' ? 'school' : item.entity_type === 'room_item' || item.entity_type === 'room_zone' ? 'room' : item.entity_type === 'idea' ? 'ideas' : 'all';
const linkFor = (item: ActivityLogEntry) => item.entity_type === 'settings' ? '/ajustes' : ({ tasks: '/tareas', money: '/finanzas', projects: '/proyectos', goals: '/metas', school: '/prepa', room: '/habitacion', ideas: '/ideas', all: '/historial' })[filterFor(item)];
const actionLabel: Record<string, string> = { 'task.created': 'Tarea creada', 'task.completed': 'Tarea terminada', 'task.reopened': 'Tarea reabierta', 'task.updated': 'Tarea actualizada', 'task.deleted': 'Tarea eliminada', 'finance.transaction_created': 'Movimiento registrado', 'finance.transaction_updated': 'Movimiento actualizado', 'finance.transaction_deleted': 'Movimiento eliminado', 'finance.payment_marked': 'Pago marcado', 'finance.saving_updated': 'Ahorro actualizado', 'project.created': 'Proyecto creado', 'project.updated': 'Proyecto actualizado', 'project.status_changed': 'Estado de proyecto actualizado', 'goal.created': 'Meta creada', 'goal.updated': 'Meta actualizada', 'goal.progress_updated': 'Progreso de meta actualizado', 'school.enrollment_configured': 'Cursado configurado', 'school.payment_marked': 'Pago escolar registrado', 'school.grade_recorded': 'Calificación registrada', 'room.status_changed': 'Habitación actualizada', 'room.day_reset': 'Día reiniciado', 'idea.created': 'Idea guardada', 'idea.updated': 'Idea actualizada', 'idea.archived': 'Idea archivada', 'idea.converted': 'Idea convertida', 'settings.updated': 'Ajustes actualizados', 'data.imported': 'Respaldo importado' };
export function HistoryPage() { const [items, setItems] = useState<ActivityLogEntry[]>([]); const [filter, setFilter] = useState<Filter>('all'); useEffect(() => { queueMicrotask(() => { void createLocalActivityRepository().list().then(setItems).catch(() => {}); }); }, []); const visible = useMemo(() => filter === 'all' ? items : items.filter((item) => filterFor(item) === filter), [items, filter]); return <main className="foundation-page history-page"><PageHeader title="Historial" intro="Lo que realmente ha ocurrido en tu espacio."/><div className="history-filters">{(Object.keys(labels) as Filter[]).map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{labels[item]}</button>)}</div>{visible.length ? <div className="history-timeline">{visible.map((item, index) => <article key={item.id} className="history-event"><span className={`history-dot ${filterFor(item)}`}/><div><small>{index === 0 || new Date(visible[index - 1].occurred_at).toDateString() !== new Date(item.occurred_at).toDateString() ? new Intl.DateTimeFormat('es-MX', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(item.occurred_at)) : new Intl.DateTimeFormat('es-MX', { hour: 'numeric', minute: '2-digit' }).format(new Date(item.occurred_at))}</small><b>{actionLabel[item.action] ?? item.action}</b>{typeof item.metadata.title === 'string' && <p>{item.metadata.title}</p>}{typeof item.metadata.name === 'string' && <p>{item.metadata.name}</p>}{typeof item.metadata.content === 'string' && <p>{item.metadata.content}</p>}</div><Link href={linkFor(item)} aria-label="Abrir entidad">›</Link></article>)}</div> : <div className="module-empty"><span>○</span><p>No hay actividad real en este filtro todavía.</p></div>}</main>; }
