'use client';

import { useEffect, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { getSupabaseBrowserClient, isSupabaseConfigured, setDataMode } from '../../lib/supabase/client';
import { loadOrMigrateDatabase } from '../../lib/persistence/migrations';
import { LOCAL_UPLOAD_KEY, LOCAL_UPLOAD_MARKER, uploadDatabaseToSupabase } from '../../lib/persistence/local-to-supabase';

type State = 'loading' | 'signed-out' | 'migrating' | 'ready' | 'error';
const today = () => new Date().toLocaleDateString('en-CA');
const LOCAL_ACCESS_KEY = 'mi-habitacion:local-access';

export function AuthGate({ children }: { children: React.ReactNode }) {
  const [state,setState]=useState<State>(isSupabaseConfigured()?'loading':'ready'); const [session,setSession]=useState<Session|null>(null); const [mode,setMode]=useState<'login'|'signup'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [message,setMessage]=useState('');
  useEffect(()=>{if(!isSupabaseConfigured()){setDataMode('local');return;}const supabase=getSupabaseBrowserClient();let preparing:string|null=null;const prepare=async(current:Session|null)=>{setSession(current);if(!current){preparing=null;setDataMode('local');setState(localStorage.getItem(LOCAL_ACCESS_KEY)==='true'?'ready':'signed-out');return;}if(preparing===current.user.id)return;preparing=current.user.id;setDataMode('remote');const marker=localStorage.getItem(LOCAL_UPLOAD_MARKER);if(marker===`${current.user.id}:${LOCAL_UPLOAD_KEY}`){setState('ready');preparing=null;return;}setState('migrating');try{const db=loadOrMigrateDatabase(localStorage,today());await uploadDatabaseToSupabase(supabase,current.user.id,db);localStorage.setItem(LOCAL_UPLOAD_MARKER,`${current.user.id}:${LOCAL_UPLOAD_KEY}`);setState('ready');}catch(cause){setMessage(cause instanceof Error?cause.message:'No se pudo completar la migración.');setState('error');}finally{preparing=null;}};void supabase.auth.getSession().then(({data})=>prepare(data.session));const{data}=supabase.auth.onAuthStateChange((_event,current)=>{void prepare(current);});return()=>data.subscription.unsubscribe();},[]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setMessage('');setState('loading');const supabase=getSupabaseBrowserClient();const result=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{display_name:name}}});if(result.error){setMessage(result.error.message);setState('signed-out');return;}if(mode==='signup'&&!result.data.session){setMessage('Revisa tu correo para confirmar la cuenta.');setState('signed-out');}};
  const useLocal=()=>{localStorage.setItem(LOCAL_ACCESS_KEY,'true');setDataMode('local');setState('ready');};
  const showAuth=()=>{localStorage.removeItem(LOCAL_ACCESS_KEY);setState('signed-out');};
  if(state==='ready')return <>{children}{session?<button type="button" className="auth-session-button" onClick={()=>void getSupabaseBrowserClient().auth.signOut()} aria-label="Cerrar sesión">Salir</button>:isSupabaseConfigured()&&<button type="button" className="auth-session-button" onClick={showAuth}>Conectar</button>}</>;
  if(state==='loading'||state==='migrating')return <main className="auth-page"><section className="auth-card" aria-live="polite"><span className="auth-mark">⌂</span><h1>Mi habitación</h1><p>{state==='migrating'?'Guardando tus datos locales de forma segura…':'Preparando tu espacio…'}</p></section></main>;
  if(state==='error')return <main className="auth-page"><section className="auth-card"><span className="auth-mark">!</span><h1>No pudimos conectar tu espacio</h1><p>{message}</p><button className="auth-primary" onClick={()=>window.location.reload()}>Reintentar</button><button className="auth-secondary" onClick={useLocal}>Continuar con datos locales</button><small>Tus datos originales no fueron eliminados.</small></section></main>;
  return <main className="auth-page"><section className="auth-card"><span className="auth-mark">⌂</span><p className="foundation-page__eyebrow">Mi espacio personal</p><h1>{mode==='login'?'Bienvenido de vuelta':'Crea tu espacio'}</h1><p>{mode==='login'?'Entra para ver tus datos en cualquier dispositivo.':'Tus datos quedarán protegidos en tu cuenta.'}</p><form onSubmit={submit}>{mode==='signup'&&<label>Nombre<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label>}<label>Correo<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Contraseña<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'}/></label>{message&&<p className="auth-error" role="alert">{message}</p>}<button className="auth-primary" type="submit">{mode==='login'?'Iniciar sesión':'Crear cuenta'}</button></form><button className="auth-switch" type="button" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('');}}>{mode==='login'?'¿Primera vez? Crear cuenta':'Ya tengo cuenta'}</button><button className="auth-secondary" type="button" onClick={useLocal}>Continuar solo en este dispositivo</button></section></main>;
}
