'use client';
import { useEffect, useState } from 'react';
import { BottomSheet } from '../../components/ui/BottomSheet';
import { LOCAL_PROFILE_ID } from '../../lib/persistence/schema';
import { useProjects } from '../projects/use-projects';
import type { Idea } from './domain';
import { notifyIdeasChanged } from './events';
import { prepareIdeaSave } from './service';
import { useIdeas } from './use-ideas';
const createId = () => globalThis.crypto.randomUUID();
export function IdeaComposer({ open, idea, onClose }: { open: boolean; idea: Idea | null; onClose: () => void }) { const { repository } = useIdeas(); const { projects } = useProjects(); const [content, setContent] = useState(''); const [details, setDetails] = useState(false); const [area, setArea] = useState(''); const [projectId, setProjectId] = useState(''); const [error, setError] = useState(''); useEffect(() => { if (open) queueMicrotask(() => { setContent(idea?.content ?? ''); setArea(idea?.area ?? ''); setProjectId(idea?.project_id ?? ''); setDetails(Boolean(idea?.area || idea?.project_id)); setError(''); }); }, [open, idea]); const save = async () => { try { const mutation = prepareIdeaSave(LOCAL_PROFILE_ID, content, new Date().toISOString(), createId, idea ?? undefined, area || null, projectId || null); await repository.save(mutation.idea, mutation.activity); notifyIdeasChanged(); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo guardar.'); } }; return <BottomSheet open={open} title={idea ? 'Editar idea' : 'Nueva idea'} onClose={onClose}><label className="idea-prompt">¿Qué se te ocurrió?</label><textarea className="idea-capture" autoFocus={open} rows={4} value={content} onChange={(event) => setContent(event.target.value)} placeholder="Escríbelo antes de que se vaya…"/><button className="task-details-toggle" onClick={() => setDetails((value) => !value)}>Organizar después <span>{details ? '−' : '+'}</span></button>{details && <div className="task-details"><label className="task-form-label">Área opcional</label><input className="task-input" value={area} onChange={(event) => setArea(event.target.value)}/><label className="task-form-label">Proyecto opcional</label><select className="task-select" value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Sin proyecto</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></div>}{error && <p className="task-form-error">{error}</p>}<button className="task-save-button" onClick={save}>Guardar idea</button></BottomSheet>; }
