'use client';
import { useEffect, useMemo, useState } from 'react';
import { PageHeader } from '../../components/ui/PageHeader';
import { LOCAL_PROFILE_ID } from '../../lib/persistence/schema';
import { useFinance } from '../finance/use-finance';
import { requestFinanceCreation } from '../finance/events';
import { requestTaskCreationForProject, notifyTasksChanged, requestTaskEdit } from '../tasks/events';
import { prepareTaskUpdate } from '../tasks/service';
import { useTasks } from '../tasks/use-tasks';
import type { ActivityLogEntry } from '../activity/domain';
import { PROJECT_PRIORITY_LABEL, PROJECT_STATUSES, PROJECT_STATUS_LABEL, type ProjectStatus } from './domain';
import { notifyProjectsChanged, requestProjectCreation, requestProjectEdit } from './events';
import { prepareProjectStatusChange } from './service';
import { useProjects } from './use-projects';

const createId = () => globalThis.crypto.randomUUID();
const money = (value: number) => new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(value);
export function ProjectsPage() {
  const { projects, repository } = useProjects(); const { tasks, repository: taskRepository } = useTasks(); const { transactions } = useFinance();
  const [selectedId, setSelectedId] = useState<string | null>(null); const [activity, setActivity] = useState<ActivityLogEntry[]>([]); const [linking, setLinking] = useState(false);
  const selected = projects.find((item) => item.id === selectedId) ?? null;
  const relatedTasks = useMemo(() => selected ? tasks.filter((item) => item.project_id === selected.id) : [], [tasks, selected]);
  const relatedTransactions = useMemo(() => selected ? transactions.filter((item) => item.project_id === selected.id) : [], [transactions, selected]);
  useEffect(() => { if (!selectedId) return; void repository.related(selectedId).then((value) => setActivity(value.activity)).catch(() => {}); }, [repository, selectedId, projects]);
  const changeStatus = async (status: ProjectStatus) => { if (!selected) return; const mutation = prepareProjectStatusChange(LOCAL_PROFILE_ID, selected, status, new Date().toISOString(), createId); if (mutation.activity) { await repository.save(mutation.project, mutation.activity); notifyProjectsChanged(); } };
  const linkTask = async (taskId: string) => { if (!selected) return; const task = tasks.find((item) => item.id === taskId); if (!task) return; const mutation = prepareTaskUpdate(LOCAL_PROFILE_ID, task, { project_id: selected.id }, new Date().toISOString(), createId); await taskRepository.save(mutation.task, mutation.activity); notifyTasksChanged(); };
  if (selected) return <main className="foundation-page"><button className="back-link" onClick={() => setSelectedId(null)}>← Proyectos</button><header className="project-hero"><span className={`project-icon ${selected.color}`}>{selected.icon}</span><div><span>{selected.type}</span><h1>{selected.name}</h1><p>{selected.objective || 'Sin objetivo escrito todavía.'}</p></div><button onClick={() => requestProjectEdit(selected.id)}>Editar</button></header><div className="project-status-line">{PROJECT_STATUSES.map((status) => <button key={status} className={selected.status === status ? 'active' : ''} onClick={() => changeStatus(status)}>{PROJECT_STATUS_LABEL[status]}</button>)}</div><div className="project-detail-grid"><section className="module-section"><div className="module-section__heading"><h2>Tareas</h2><span><button onClick={() => setLinking((value) => !value)}>Vincular</button><button onClick={() => requestTaskCreationForProject(selected.id)}>+ Nueva</button></span></div>{linking && <div className="link-picker">{tasks.filter((item) => !item.project_id).map((task) => <button key={task.id} onClick={() => linkTask(task.id)}>+ {task.title}</button>)}{tasks.every((item) => item.project_id) && <small>No hay tareas sin proyecto.</small>}</div>}{relatedTasks.length ? relatedTasks.map((task) => <button className="simple-row interactive" key={task.id} onClick={() => requestTaskEdit(task.id)}><span><b>{task.title}</b><small>{task.status === 'completed' ? 'Terminada' : 'Pendiente'}</small></span><i>›</i></button>) : <Empty text="Aún no hay tareas relacionadas."/>}</section><section className="module-section"><div className="module-section__heading"><h2>Finanzas</h2><button onClick={() => requestFinanceCreation('expense', selected.id)}>+ Movimiento</button></div>{relatedTransactions.length ? relatedTransactions.map((item) => <article className="simple-row" key={item.id}><span><b>{item.category}</b><small>{item.date}</small></span><strong>{item.type === 'income' ? '+' : '−'}{money(item.amount)}</strong></article>) : <Empty text="Aún no hay movimientos relacionados."/>}</section><section className="module-section"><h2>Notas base</h2><p className="base-notes">{selected.notes || 'Sin notas todavía.'}</p></section><section className="module-section"><h2>Actividad</h2>{activity.length ? activity.slice(0, 6).map((entry) => <article className="activity-row" key={entry.id}><span>•</span><div><b>{entry.action === 'project.created' ? 'Proyecto creado' : entry.action === 'project.status_changed' ? 'Estado actualizado' : 'Proyecto editado'}</b><small>{new Date(entry.occurred_at).toLocaleDateString('es-MX')}</small></div></article>) : <Empty text="Sin actividad todavía."/>}</section></div></main>;
  return <main className="foundation-page"><PageHeader title="Proyectos" intro="Espacios concretos para lo que estás construyendo."/><div className="module-toolbar"><span>{projects.length} {projects.length === 1 ? 'proyecto' : 'proyectos'}</span><button onClick={requestProjectCreation}>+ Nuevo proyecto</button></div>{projects.length ? <div className="project-cards">{projects.map((project) => <button className="project-card foundation-card" key={project.id} onClick={() => setSelectedId(project.id)}><span className={`project-icon ${project.color}`}>{project.icon}</span><span><b>{project.name}</b><small>{PROJECT_STATUS_LABEL[project.status]} · {PROJECT_PRIORITY_LABEL[project.priority]}</small><p>{project.objective || 'Sin objetivo escrito'}</p></span><i>›</i></button>)}</div> : <Empty text="Crea un proyecto para reunir tareas, movimientos y notas."/>}</main>;
}
function Empty({ text }: { text: string }) { return <div className="module-empty"><span>○</span><p>{text}</p></div>; }
