'use client';
import { useEffect, useState } from 'react';
import { BottomSheet } from '../../components/ui/BottomSheet';
import { LOCAL_PROFILE_ID } from '../../lib/persistence/schema';
import { PROJECT_PRIORITY_LABEL, PROJECT_STATUSES, PROJECT_STATUS_LABEL, type Project, type ProjectInput, type ProjectPriority } from './domain';
import { notifyProjectsChanged } from './events';
import { prepareProjectSave } from './service';
import { useProjects } from './use-projects';

const createId = () => globalThis.crypto.randomUUID();
const blank: ProjectInput = { name: '', status: 'idea', type: 'Personal', priority: 'none', objective: '', target_date: null, icon: '✦', color: 'sage', notes: null };
export function ProjectComposer({ open, project, onClose }: { open: boolean; project: Project | null; onClose: () => void }) {
  const { repository } = useProjects(); const [input, setInput] = useState<ProjectInput>(blank); const [error, setError] = useState('');
  useEffect(() => { if (open) queueMicrotask(() => { setInput(project ? { name: project.name, status: project.status, type: project.type, priority: project.priority, objective: project.objective, target_date: project.target_date, icon: project.icon, color: project.color, notes: project.notes } : blank); setError(''); }); }, [open, project]);
  const field = <K extends keyof ProjectInput>(key: K, value: ProjectInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const save = async () => { try { const mutation = prepareProjectSave(LOCAL_PROFILE_ID, input, new Date().toISOString(), createId, project ?? undefined); await repository.save(mutation.project, mutation.activity); notifyProjectsChanged(); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo guardar.'); } };
  return <BottomSheet open={open} title={project ? 'Editar proyecto' : 'Nuevo proyecto'} onClose={onClose}><div className="identity-row"><select aria-label="Icono" value={input.icon} onChange={(event) => field('icon', event.target.value)}>{['✦','⌂','◎','◇','☀'].map((icon) => <option key={icon}>{icon}</option>)}</select><input className="task-title-input" value={input.name} onChange={(event) => field('name', event.target.value)} placeholder="Nombre del proyecto"/></div><div className="finance-form-grid"><label><span>Tipo</span><input value={input.type} onChange={(event) => field('type', event.target.value)}/></label><label><span>Fecha objetivo</span><input type="date" value={input.target_date ?? ''} onChange={(event) => field('target_date', event.target.value || null)}/></label></div><fieldset className="task-form-fieldset"><legend>Estado</legend><div className="choice-wrap">{PROJECT_STATUSES.map((status) => <button key={status} className={input.status === status ? 'active' : ''} onClick={() => field('status', status)}>{PROJECT_STATUS_LABEL[status]}</button>)}</div></fieldset><fieldset className="task-form-fieldset"><legend>Prioridad</legend><div className="task-priority-line">{(['none','important','main'] as ProjectPriority[]).map((priority) => <button key={priority} className={input.priority === priority ? 'active' : ''} onClick={() => field('priority', priority)}>{PROJECT_PRIORITY_LABEL[priority]}</button>)}</div></fieldset><label className="task-form-label">Objetivo</label><textarea className="task-textarea" rows={2} value={input.objective} onChange={(event) => field('objective', event.target.value)} placeholder="¿Qué quieres conseguir?"/><label className="task-form-label">Notas base</label><textarea className="task-textarea" rows={3} value={input.notes ?? ''} onChange={(event) => field('notes', event.target.value || null)}/>{error && <p className="task-form-error">{error}</p>}<button className="task-save-button" onClick={save}>Guardar proyecto</button></BottomSheet>;
}
